docs: add blog post for ESLint fixers
eslint/eslint.org pull request #230
Opened 2022-06-14 00:33 UTC by bradzacher

Context: https://twitter.com/slicknet/status/1535417827502354432

This is a first draft of a blog post about fixers and their IDE integration.
I'm not entirely sold on the preamble about CLI fixes, but we can work together to figure out what's best!

[📄 View Rendered](https://github.com/bradzacher/new.eslint.org/blob/823662192169ae1083912a93215cd03b600aee7c/src/content/blog/2022-06-XX-ESLint-Fixers.md)

2022-06-16 01:01 UTC, nzakas requested changes
Thanks for this! Just did a quick once over because we haven’t finalized our process or the website yet.

Can you create a top-level folder in the repo called “drafts” and move your file into that? You can also remove the date from the filename, as we will figure out what date to publish on at a later time.

We are working on pushing the new site live so your patience is appreciated!

2022-06-28 00:52 UTC, nzakas commented
Please rebase on top of main to get the latest setup. We are now asking posts be saved in src/content/drafts. There is also a README in that directory with more instructions.

2022-07-20 22:09 UTC, nzakas commented
@bradzacher just checking in to see if you're still working on this?

2022-07-20 22:11 UTC, bradzacher commented
Yes it's still on my todo list!
I've just been short on time lately between work and my infant son.
I think I'll have some time next week to finish this off.

2022-07-20 22:16 UTC, nzakas commented
No problem! Take your time.

2022-08-03 17:44 UTC, amareshsm commented on src/content/blog/2022-06-XX-ESLint-Fixers.md
> +A more granular approach is to leverage your [IDE integration](https://eslint.org/docs/user-guide/integrations#editors) to selectively apply fixers as you code. Most IDEs will expose a “quick action”
```suggestion
A more granular approach is to leverage your [IDE integration](https://eslint.org/docs/user-guide/integrations#editors) to selectively apply fixers as you code. Most IDEs will expose a “quick action” or “quick fix” menu which allows you to manually choose to apply the fixer when a problem is reported.
```

2022-11-02 17:57 UTC, nzakas commented
Going to close this for now. When you're ready to resubmit, feel free to open a new PR.

2022-11-02 17:57 UTC, closed without merging