feat: blog: Vue Uncategorized rules to have a better life
eslint/eslint.org pull request #295
Opened 2022-08-03 08:13 UTC by BobToninho

In this blog post I explain a bunch of Vue related rules, their advantages and how I use them to improve my overall DX. I'm aware there's not a lot of copy, so let me know if something more is needed.

2022-08-03 13:16 UTC, amareshsm commented on src/content/drafts/vue-rules-better-life.md
> +The PascalCase convention for component names helps distinguish more clearly a component from an actual HTML element. Additionaly, depending on the theme, your editor or IDE will highlight a componen
```suggestion
The PascalCase convention for component names helps distinguish more clearly a component from an actual HTML element. Additionally, depending on the theme, your editor or IDE will highlight a component in PascalCase with a different color with respect to an actual HTML element. In my experience, I find this small tweak especially useful when managing big components.
```

2022-08-03 13:16 UTC, amareshsm commented on src/content/drafts/vue-rules-better-life.md
> +I spent some time digging into the *uncategorized* category to see what can be useful to help avoiding distractions in commits and, of course, to enforce the same style in all parts of a Vue project.
```suggestion
I spent some time digging into the *uncategorized* category to see what can be useful to help avoid distractions in commits and, of course, to enforce the same style in all parts of a Vue project. In my opinion, all Vue projects should use the Recommended category, which enforces a lot (if not all) of the topics mentioned in the [style guide](https://vuejs.org/style-guide/).
```

2022-08-05 01:24 UTC, nzakas requested changes
Thanks for submitting. This is pretty light on content, so as-is, we can’t accept it for the blog. While we don’t mind opinion pieces, it seems like there is nothing more than “this is how I like to configure these rules,” which I’m not sure is enough for a post.

I’d suggest thinking through a few questions to clarify if you think there is a story here:

- Why would ESLint users want to read this? What benefit are they receiving? Why would they read this instead of something else?
- Same for Vue users?
- What are the benefits you’ve seen, not just “it makes code the way I like it,” but practically speaking? Did you reduce bugs? Did it help in another way?
- What is the conclusion you’d like readers to take away?

2022-08-05 01:24 UTC, nzakas commented on src/_includes/partials/author_bios/BobToninho.md
> +Young freelance developer
Please expand your bio here. We generally like the form “Bob Toninho is a…. He…. And I’m his spare time he….”

2022-08-05 01:24 UTC, nzakas commented on src/content/drafts/vue-rules-better-life.md
> +title: Vue Uncategorized rules to have a better life
Maybe a bit clearer?
```suggestion
title: Exploring useful uncategorized rules in the Vue ESLint plugin
```

2022-08-05 01:24 UTC, nzakas commented on src/content/drafts/vue-rules-better-life.md
> +teaser: "Some useful Uncategorized Vue rules that will make your daily life a little easier."
```suggestion
teaser: "The Vue ESLint plugin has several rules that are uncategorized and it turns out many will make your daily life a little easier."
```

2022-08-05 01:24 UTC, nzakas commented on src/content/drafts/vue-rules-better-life.md
> +## Introduction
We don’t need a heading here. The first few paragraphs always considered the introduction. 
```suggestion
```

2022-08-05 01:24 UTC, nzakas commented on src/content/drafts/vue-rules-better-life.md
> +The [esling-plugin-vue](https://eslint.vuejs.org/) plugin divides its rules in the following categories:
```suggestion
The official Vue ESLint plugin, [eslint-plugin-vue](https://eslint.vuejs.org/), groups its rules into the following categories:
```

2022-08-05 01:24 UTC, nzakas commented on src/content/drafts/vue-rules-better-life.md
> +I spent some time digging into the *uncategorized* category to see what can be useful to help avoid distractions in commits and, of course, to enforce the same style in all parts of a Vue project. In
Some cleanup, and the last sentence doesn’t fit with the paragraph or the rest of the article. 

```suggestion
I spent some time digging into the uncategorized category to see which rules might be useful to help avoid problems in commits and to enforce the same style in all parts of a Vue project. In my opinion, all Vue projects should use the Recommended category, which enforces a lot (if not all) of the topics mentioned in the [style guide](https://vuejs.org/style-guide/).
```

2022-08-30 17:42 UTC, nzakas commented
Closing as we won't be moving forward here.

2022-08-30 17:42 UTC, closed without merging